package model.tribe;

public enum DiplomacyResult {
    SUCCESS,
    TRIBE_NOT_DISCOVERED,
    TRIBE_DEFEATED,
    ALREADY_ENEMY,
    NOT_ENEMY,
    RELATION_TOO_LOW,
    INSUFFICIENT_RESOURCES,
    ALLIANCE_RESTRICTED,
    RECENT_MISSION_FAILURE,
    PEACE_ALREADY_PENDING,
    INVALID_REQUEST
}
